apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'ranaaamandeep682@gmail.com'
      smtp_auth_username: 'ranaaamandeep682@gmail.com'
      smtp_auth_password: 'wqbz bkaw iuwe uhhk'

    route:
      receiver: "email-notification"
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 5m

    receivers:
      - name: 'email-notification'
        email_configs:
          - to: 'ranaaamandeep682@gmail.com'
            send_resolved: true
