apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    rule_files:
      - "/etc/prometheus/rules/alert-rules.yaml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 'alertmanager.monitoring.svc.cluster.local:9093'

    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        static_configs:
          - targets: ['localhost:8080']

      - job_name: 'python-app'
        static_configs:
          - targets: ['python-app-service.default.svc.cluster.local:8000']

