apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: amandeeprana/my-python-app:__IMAGE_TAG__
        imagePullPolicy: Always  # <-- Use this if local image
        ports:
        - containerPort: 8000

