apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: amandeeprana/my-python-app:1f482bfc4af88ba489cf0eead8946a11a8ea7c1c
        imagePullPolicy: Always  # <-- Use this if local image
        ports:
        - containerPort: 8000

