name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Login to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Configure Kubeconfig
        run: |
          # Create the .kube directory
          mkdir -p $HOME/.kube
          # Create a new kubeconfig file from the secret
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config
          # Set correct permissions
          chmod 600 $HOME/.kube/config
          # THIS IS THE FIX: Replace the server IP with localhost to fix the TLS handshake timeout
          sed -i 's|server:.*|server: https://localhost:6443|g' $HOME/.kube/config
  
      - name: Deploy to K3s Cluster
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
